### ISSUE TITLE
Better defaults

### ISSUE THREAD

**Issue by Inkane** [ccr-tools/aur2ccr#8]
aur2ccr needs to be more strict, to avoid that users use it to install software from arch linux, which breaks their systems.

**Comment by rshipp** [comment]
OK, so what parts do we need to change? Obviously the question about "already in the repos, are you sure?" needs to go, but what else can we do to make it harder for people to break their system? Remove all built *.pkg.tar.xz files, and get rid of the -i option? Go back to the olden days, when aur2ccr did not install dependencies, and just complained if they weren't already there?

**Comment by Inkane** [comment]
george2:   Dependency fetching should stay in my opinion, this is to useful. We should get rid of the -i option, so that nobody thinks aur2ccr is a proper way to install software from Arch, as if it were from the repos. Removing the *.pkg.tar.xz file would force the user to run makepkg, thus read at least a bit about how to build packages. Therefore it should be done.

And I would print a more descriptive error when a package is already in the repos, telling the user why he shouldn't try this.

**Comment by rshipp** [comment]
OK, I've made some changes in a new 'breakitall' branch, so do whatever you want to the descriptions, and I'll push our changes to CCR tonight. I've added some more disclaimer stuff, removed -i, and had it rm all *pkg.tar.xz packages that are built with makepkg -s. 

About the dependencies, I just meant, should we fetch all dependencies, but not install them? If we do that, all packages possible will be built, but those without depends will have source packages only (no makepkg -s). This is the way aur2ccr used to work. It just printed "dependency X of Y cannot be found, this package cannot be tested".

I am adding special, undocumented variables that can be used to force aur2ccr to work the way it does now, because I would like to still be able to use these features. Any TU or advanced user should still be able to use aur2ccr as normal, without these restrictions.

**Comment by Inkane** [comment]
Nice work. IMHO anyone who knows how to build proper packages will know how to set the hidden variables, so that's a good approach. 

About dependencies: As long as there is a recursive dependency fetching I can't see any problems. Maybe generate a package->depends list, where all packages that aren't build are listed with their dependencies, so that the users can check what needs to be installed.

**Comment by rshipp** [comment]
Good idea. I'll work on getting that list added.
I've also made some long-needed changes to the arch-repo-searching code, making it way faster, and getting rid of sudo. Do you think that should be added to the --search option, or is that just encouragement to install packages from the Arch repos? I'd like it for myself, so I'll add it as another hidden feature if you think it would be bad to leave it on by default.

**Comment by Inkane** [comment]
That search change doesn't sound dangerous and is really convenient, but 
better ask Anke about it.

**Comment by rshipp** [comment]
This was done years ago, closing.
